### PR TITLE
fix: don't panic when piping

### LINKED ISSUE #79: panic when piping to `head`
Piping the output of `rbw list` to `head` results in a panic:

```
$ rbw list | head -n 1
<first entry>
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:935:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Piping it into `tail` doesn't produce a panic, probably due to the pipe being closed after instead of before `rbw` is done writing to it.

I haven't looked into it much, but this instance of the panic seems to be cause by the following `println!` macro call:
https://github.com/doy/rbw/blob/94a0009fc2067bab549b194ca976a71e7395f403/src/bin/rbw/commands.rs#L533

A fix would be to replace this with a `write!`, which returns an error that can be handled.

If a fix is desired I might have time to look into it.

### PR DESCRIPTION
**Pull request by Witcher01**
Piping stdout to something like `head`, which closes rbw's stdout before
it's done writing everything, causes a panic.
The panic is circumvented by using `writeln!` instead of `println!` and
ignoring the error when it's of kind `BrokenPipe`.
Closes #79

### CODE REVIEW

**Comment by svenstaro** [comment]
@doy could you take a look at this?

**Review by kpcyrd — APPROVED** [review]

**Comment by svenstaro** [comment]
@doy ping

File: src/bin/rbw/commands.rs [hunk 1]
```diff
@@ -530,7 +532,13 @@ pub fn list(fields: &[String]) -> anyhow::Result<()> {
                 ),
             })
             .collect();
-        println!("{}", values.join("\t"));
+
+        // write to stdout but don't panic when pipe get's closed
+        // this happens when piping stdout in a shell
```
Comment (svenstaro) [inline src/bin/rbw/commands.rs:537]:
```suggestion
        // Write to stdout but don't panic when pipe gets closed
        // which is what happens when piping stdout in a shell.
```

**Review by svenstaro — CHANGES_REQUESTED** [review]
